# Generated by Django 3.2.7 on 2021-09-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='date_of_birth',
        ),
    ]
