# Generated by Django 3.2.7 on 2021-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
